footer/urls.py
from django import views
from . import views
from django.urls import path

app_name = 'footer'

urlpatterns = [
    path('politica-de-retur/', views.politica_de_retur, name='politica_de_retur'),
    path('touch-of-gold-club/', views.touch_of_gold_club, name='touch_of_gold_club'),
    path('responsabilitate/', views.responsabilitate, name='responsabilitate'),
    path('setari-cookieuri/', views.setari_cookieuri, name='setari_cookieuri'),

]

online_store2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('store_basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('footer/', include('footer.urls', namespace='footer')),
    # path('payment/', include('payment.urls', namespace='payment')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django import views
from . import views
from django.urls import path

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='home'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    # path('shop/<slug:subcategory_slug>/', views.subcategory_list, name='subcategory_list'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}Touch of Gold{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.7.4/dist/css/foundation.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'online_store/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'basket/css/basket.css' %}">
    <link rel="stylesheet" href="{% block stylesheet %}{% endblock %}">

<style>
body{
    margin: 0;
    padding: 0;
    background-color: rgb(246, 246, 248);
}

</style>
</head>

<body>
    <header class="pb-3">
        {% include 'navbar.html' %}
    </header>
    <main>
    <div class="container-xl">
    <div id="content">{% block content %} {% endblock %}</div>
    </div>
    </main>

    <footer class="container py-5 footer">
        <hr>
        <div class="row pt-8">
            <div class="col-12 col-md">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-asterisk" viewBox="0 0 16 16">
                    <path
                        d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z" />
                </svg>
                <small class="d-block mb-3 text-muted">&copy; 2022</small>
            </div>
            <div class="col-6 col-md fs15">
                <h5>Features</h5>
                <ul class="list-unstyled">
                    <li><a class="link-secondary text-decoration-none" href="{% url 'footer:politica_de_retur' %}">Politica de retur</a></li>
                    <li><a class="link-secondary text-decoration-none" href="{% url 'footer:touch_of_gold_club' %}">Touch of Gold Club</a></li>
                    <li><a class="link-secondary text-decoration-none" href="{% url 'footer:responsabilitate' %}">Responsabilitate</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Protecția datelor</a></li>
                    <li><a class="link-secondary text-decoration-none" href="{% url 'footer:setari_cookieuri' %}">Setări cookie-uri</a></li>
                </ul>
            </div>
            <div class="col-6 col-md fs15">
                <h5>Contact</h5>
                <ul class="list-unstyled">
                    <li><a class="link-secondary text-decoration-none" href="#">Date de contact</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Locuri vacante</a></li>
                </ul>
            </div>
            <div class="col-6 col-md fs15">
                <h5>Resources</h5>
                <ul class="list-unstyled">
                    <li><a class="link-secondary text-decoration-none" href="#">Business</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Education</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Government</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Gaming</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>About</h5>
                <ul class="list-unstyled">
                    <li><a class="link-secondary text-decoration-none" href="#">Team</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
                </ul>
            </div>
        </div>
    </footer>
</body>
</html>

templates/sub_base.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheet %}{% static 'account/css/account.css' %}{% endblock %}
{% block content %}
<div class="container">
  <div class="login d-flex align-items-center">
    <div class="col-12 col-md-12 col-lg-12 mx-auto">
      {% block sub_content %}{% endblock %}
    </div>
  </div>
</div>
{% endblock %}