account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/register/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),

    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/password_reset/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'),

    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"), name='delete_confirmation'),

    # Addresses
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    path("user_orders/", views.user_orders, name="user_orders"),

    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
]

online_store2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('store_basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('footer/', include('footer.urls', namespace='footer')),
    # path('payment/', include('payment.urls', namespace='payment')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django import views
from . import views
from django.urls import path

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='home'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    # path('shop/<slug:subcategory_slug>/', views.subcategory_list, name='subcategory_list'),

]

store_basket/urls.py
from django.urls import path

from store_basket import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete_product/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),

]

store/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey

from online_store2 import settings


class Category(MPTTModel):
    """
    Category Table implimented with MPTT.
    """

    name = models.CharField(
        verbose_name=_("Category Name"),
        help_text=_("Required and unique"),
        max_length=255,
        unique=True,
    )
    slug = models.SlugField(verbose_name=_("Category safe URL"), max_length=255, unique=True)
    parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, related_name="children")
    is_active = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])

    def __str__(self):
        return self.name


class ProductType(models.Model):
    """
    ProductType Table will provide a list of the different types
    of products that are for sale.
    """

    name = models.CharField(verbose_name=_("Product Name"), help_text=_("Required"), max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
      # RESTRICT e pt a preveni stergerea, in caz de stergem product_types

    class Meta:
        verbose_name = _("Product Type")
        verbose_name_plural = _("Product Types")

    def __str__(self):
        return self.name


class ProductSpecification(models.Model):
    """
    The Product Specification Table contains product
    specifiction or features for the product types.
    """

    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    name = models.CharField(verbose_name=_("Name"), help_text=_("Required"), max_length=255)

    class Meta:
        verbose_name = _("Product Specification")
        verbose_name_plural = _("Product Specifications")

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    The Product table contining all product items.
    """

    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    title = models.CharField(
        verbose_name=_("title"),
        help_text=_("Required"),
        max_length=255,
    )
    description = models.TextField(verbose_name=_("description"), help_text=_("Not Required"), blank=True)
    slug = models.SlugField(max_length=255)
    regular_price = models.DecimalField(
        verbose_name=_("Regular price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    discount_price = models.DecimalField(
        verbose_name=_("Discount price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    is_active = models.BooleanField(
        verbose_name=_("Product visibility"),
        help_text=_("Change product visibility"),
        default=True,
    )
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)


    class Meta:
        ordering = ("-created_at",)
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])

    def __str__(self):
        return self.title


class ProductSpecificationValue(models.Model):
    """
    The Product Specification Value table holds each of the
    products individual specification or bespoke features.
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT)
    value = models.CharField(
        verbose_name=_("value"),
        help_text=_("Product specification value (maximum of 255 words"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("Product Specification Value")
        verbose_name_plural = _("Product Specification Values")

    def __str__(self):
        return self.value


class ProductImage(models.Model):
    """
    The Product Image table.
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_image")
    image = models.ImageField(
        verbose_name=_("image"),
        help_text=_("Upload a product image"),
        upload_to="images/",
        default="images/default.png",
    )
    alt_text = models.CharField(
        verbose_name=_("Alternative text"),
        help_text=_("Please add alturnative text"),
        max_length=255,
        null=True,
        blank=True,
    )
    is_feature = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")




# from django.contrib.auth.models import User
# from django.db import models
#
# from django.urls import reverse
#
#
# # reverse ne va permite sa construim un url in models (acel url din fct de jos)
# # class SubcategoryManager(models.Manager):
# #     def get_queryset(self):
# #         return super(SubcategoryManager, self).get_queryset().filter(is_active=True, in_stock=True, )
# from online_store2 import settings
#
#
# class ProductManager(models.Manager):
#     def get_queryset(self):
#         return super(ProductManager, self).get_queryset().filter(is_active=True, in_stock=True, )
#
#
# class Category(models.Model):
#     name = models.CharField(max_length=255, db_index=True)
#     slug = models.SlugField(max_length=255, unique=True)
#
#     # Slug is a newspaper term.A slug is a short label
#     # for something, containing only letters, numbers, underscores or hyphens.
#     # They’re generally used in URLs.
#
#     class Meta:
#         verbose_name_plural = 'Categories'
#
#     def get_absolute_url(self):
#         return reverse('store:category_list', args=[self.slug])
#
#     # (aceasta functie creeaza legatura dintre pagina de home si cea cu categoriile->
#     # folosesc asta pt a accesa categoriile(inele, coliere etc))
#
#     def __str__(self):
#         return self.name
#
#
# # class Subcategory(models.Model):
# #     category = models.ForeignKey(Category, related_name='category', on_delete=models.CASCADE)
# #     subcategory_name = models.CharField(max_length=150, db_index=True)
# #     slug = models.SlugField(max_length=255, unique=True)
# #     # subcategories = SubcategoryManager()
# #
# #     class Meta:
# #         ordering = ('subcategory_name',)
# #         verbose_name_plural = 'Subcategories'
# #
# #     def get_absolute_url(self):
# #         return reverse('store:subcategory_list', args=[self.slug])
# #
# #     def __str__(self):
# #         return self.subcategory_name
#
#
# class Product(models.Model):
#     category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
#     # subcategory = models.ForeignKey(Subcategory, related_name='product', on_delete=models.CASCADE)
#     created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
#     product_name = models.CharField(max_length=255)
#     description = models.TextField(blank=True)
#     image = models.ImageField(upload_to='images/', default='images/default.png')
#     slug = models.SlugField(max_length=255)
#     price = models.DecimalField(max_digits=4, decimal_places=2)
#     in_stock = models.BooleanField(default=True)
#     is_active = models.BooleanField(default=True)
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)
#     objects = models.Manager()
#     products = ProductManager()
#
#     class Meta:
#         verbose_name_plural = 'Products'
#         ordering = ('-created',)
#
#     def get_absolute_url(self):
#         return reverse('store:product_detail', args=[self.slug])
#
#     #   store este aplicatia din urls care ne permite sa accesam mai usor urls urile,
#     #   product_detail este name ul din urls.py si prin store il accesam
#
#     def __str__(self):
#         return self.product_name
#

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product

# def categories(request):
#     return {
#         'categories': Category.objects.all()
#     }

def all_products(request):
    products = Product.objects.prefetch_related("product_image").filter(is_active=True)
    return render(request, 'store/index.html', {'products': products})
# store/index.html --> vine din templates

# SLUG again
# ca si cum am folosi acel cuvant din url(aparut pe baza slug)
# pentru a face un fel de query in baza de date
def product_detail(request, slug, is_active=True):
    product = get_object_or_404(Product, slug=slug)
    return render(request, 'store/single.html', {'product': product})

def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)  #asta va returna un obiect din categoria vizata(get_object_or_404)
    products = Product.objects.filter(
        category__in = category.get_descendants(include_self=True)
    )
    return render(request, 'store/category.html', {'category': category, 'products': products})

# def subcategory_list(request, subcategory_slug=None):
#     category = get_object_or_404(Category, slug=subcategory_slug)  #asta va returna un obiect din categoria vizata(get_object_or_404)
#     subcategory = Subcategory.objects.filter(category=category)
#     products = Product.objects.filter(subcategory=subcategory)
#     return render(request, 'products/subcategory_list.html', {'subcategory': subcategory, 'products': products})

templates/store/category.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="album bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
              {% for image in product.product_image.all %}
                  {% if image.is_feature %}
                      <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}"
                           alt="{{ image.image.alt_text }}">
                  {% endif %}
              {% endfor %}
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
                <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">${{product.regular_price}}</small>
              </div>
              <div class="d-flex justify-content-between align-items-center">
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/store/single.html
{% extends "base.html" %}
{% load static %}
{#{% block stylesheet %}{% static 'store/css/store.css' %}{% endblock %}#}
{% block title %}
    {{ product.name }}
{% endblock %}
{% block content %}

    <div class="container">
    {% if messages %}
        <div class="alert alert-warning" alert-{{ message.tags }}  role="alert">
            {% for message in messages %}
                {{ message|safe }}  <a href="{% url "account:wishlist" %}" class="alert-link">Your Wishlist</a>.
            {% endfor %}
        </div>
    {% endif %}
    <div class="container" style="max-width: 1000px">

        <div class="row g-3">

            <div class="col-12 d-flex justify-content-between">

            </div>

            <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
                <div class="d-grid gap-2">

                    <div class="d-flex d-flex-inline justify-content-between">
                        <div><span class="h3">${{ product.regular_price }}</span>
                            <p class="text-muted">includes tax</p>
                            <p class="text-muted">{{ product.description }}</p></div>
                        <div class="">
                            <label for="select" class="choose">Quantity</label>
                            <select id="select" class="h6 store-select-dropdown">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div>
                    </div>
                    <hr>
                    <button type="button" id="add-button" value="{{ product.id }}" class="btn btn-dark fw500">Add
                        to basket
                    </button>
                    <a href="{% url "account:user_wishlist" product.id %}" class="btn btn-outline-dark fw500"
                       role="button" aria-disabled="true">Add to Wishlist</a>
                    {#                        <button type="button" id="add-button" value="{{ product.id }}" class="btn btn-light fw500">Add#}
                    {#                            to Wishlist#}
                    {#                        </button>#}
                </div>
            </div>

            <div class="col-md-7 col-lg-7 p-0">


                <div class="card mb-3 border-0">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-body p-1">
                                <h1 class="mb-0 h2 pe-4 pb-4">{{ product.title }}</h1>
                                {% for image in product.product_image.all %}
                                    {% if image.is_feature %}
                                        <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image"
                                             src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
                                    {% else %}
                                        <img class="img-fluid d-block-inline pt-3" width="100px"
                                             alt="Responsive image" src="{{ image.image.url }}"
                                             alt="{{ image.image.alt_text }}">
                                    {% endif %}
                                {% endfor %}
                                {#                                    <div class="bg-light"><img class="img-fluid mx-auto d-block" width="400px"#}
                                {#                                                               alt="Responsive image" src="{{ product.image.url }}">#}
                                {#                                    </div>#}
                            </div>

                        </div>
                    </div>
                </div>


            </div>

        </div>
    </div>


    <script>
        $(document).on('click', '#add-button', function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "basket:basket_add" %}',
                data: {
                    productid: $('#add-button').val(),
                    productqty: $('#select option:selected').text(),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: 'post'
                },
                success: function (json) {
                    document.getElementById("basket-qty").innerHTML = json.qty
                },
                error: function (xhr, errmsg, err) {
                }
            });
        })
    </script>


{% endblock %}







{#{% extends "base.html" %}#}
{#{% load static %}#}
{#{% block title %}#}
{#    {{ product.name }}#}
{#{% endblock %}#}
{#{% block content %}#}
{#    <div class="container">#}
{#        <main class="pt-5">#}
{#            <div class="row g-3">#}
{#                <div class="col-md-5 col-lg-5 order-md-first bg-light">#}
{#                    <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image"#}
{#                         src="{{ product.image.url }}">#}
{#                </div>#}
{#                <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">#}
{#                    <h1 class="mb-0 h4">{{ product.product_name }}</h1>#}
{#                    <p><span class="lead">{{ product.category }}</span></p>#}
{#                    <p>{{ product.description|slice:":355" }}...</p>#}
{#                    <div class="border">#}
{#                        <div class="col border-bottom">#}
{#                            <div class="row p-3">#}
{#                                <div class="col-6">Hardback</div>#}
{#                                <div class="col-6 text-end"><span class="h4 fw-bold">${{ product.price }}</span></div>#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="col">#}
{#                            <div class="row p-3">#}
{#                                <div class="col-6">#}
{#                                    <label for="select">Qty</label>#}
{#                                    <select id="select">#}
{#                                        <option value="">1</option>#}
{#                                        <option value="">2</option>#}
{#                                        <option value="">3</option>#}
{#                                        <option value="">4</option>#}
{#                                    </select>#}
{##}
{#                                </div>#}
{#                                <div class="col-6 text-end">#}
                                    {#      <button type="button" id="add-button" value="product.id" class="btn btn-secondary btn-sm">Add to basket</button></div>#}
{#                                    <input type="hidden" class="product-id-{{ data.id }}" value="{{ data.id }}"/>#}
{#                                    <input type="hidden" class="product-title-{{ data.id }}" value="{{ data.title }}"/>#}
{#                                    <button type="button" class="btn btn-secondary btn-sm add-to-cart "#}
{#                                            data-index="{{ data.id }}" type="button" id="addToCartBtn">Add to basket#}
{#                                    </button>#}
{#                                </div>#}
                                {#                            		    <button class="btn btn-primary btn-sm add-to-cart" data-index="{{data.id}}" type="button" id="addToCartBtn"><i class="fa fa-shopping-cart"></i> Add to Cart</button>#}
{##}
{##}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </main>#}
{##}
{#    </div>#}
{#    <script>#}
        {#$("#addToCartBtn").on#}
{#        $(document).on('click',".addToCartBtn",function(){#}
		{#var _vm=$(this);#}
		{#var _index=_vm.attr('data-index');#}
		{#var _qty=$(".product-qty-"+_index).val();#}
{#		var _productId=$(".product-id-").val();#}
		{#var _productImage=$(".product-image-"+_index).val();#}
{#		var _productTitle=$(".product-title-").val();#}
		{#var _productPrice=$(".product-price-"+_index).text();#}
{#		// Ajax#}
{#		$.ajax({#}
{#			url:'{% url "basket:basket_add" %}',#}
{#			data:{#}
{#				'id':_productId,#}
				{#'image':_productImage,#}
				{#'qty':_qty,#}
{#				'title':_productTitle,#}
				{#'price':_productPrice#}
{#			},#}
{#			dataType:'json',#}
{#			beforeSend:function(){#}
{#				_vm.attr('disabled',true);#}
{#			},#}
{#			success:function(res){#}
{#				$(".summary").text(res.totalitems);#}
{#				_vm.attr('disabled',false);#}
{#			}#}
{#		});#}
{#        })#}
        {#$(document).on('click', '#add-button', function (e){#}
        {#    e.preventDefault();#}
        {#    $.ajax({#}
        {#        type: 'POST',#}
        {#        url: '{% url "basket:basket_add" %}',#}
        {#        data: {#}
        {#            productid: $('#add-button').val(),#}
        {#            csrfmiddlewaretoken: "{{csrf_token}}",#}
        {#            action: 'post'#}
        {#        },#}
        {#        success: function (json) {#}
        {#        },#}
        {#        error: function (xhr, errmsg, err) {}#}
        {#    });#}
{##}
{##}
{#    </script>#}
{#{% endblock content %}#}



{#{% extends "base.html" %}#}
{#{% load static %}#}
{#{% block title %}#}
{#{{ product.name }}#}
{#{% endblock %}#}
{#{% block content %}#}
{#<div class="container">#}
{#    <main class="pt-5">#}
{#        <div class="row g-3">#}
{#            <div class="col-md-5 col-lg-5 order-md-first bg-light">#}
{#                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">#}
{#            </div>#}
{#            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">#}
{#                <h1 class="mb-0 h4">{{ product.title }}</h1>#}
{#                <p><span class="lead">{{ product.author }}</span> (Author)</p>#}
{#                <p>{{ product.description|slice:":355" }}...</p>#}
{#                <div class="border">#}
{#                    <div class="col border-bottom">#}
{#                        <div class="row p-3">#}
{#                            <div class="col-6">Hardback</div>#}
{#                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.price }}</span></div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col">#}
{#                        <div class="row p-3">#}
{#                            <div class="col-6">#}
{#                                <label for="select">Qty</label>#}
{#                                <select id="select">#}
{#                                    <option value="1">1</option>#}
{#                                    <option value="2">2</option>#}
{#                                    <option value="3">3</option>#}
{#                                    <option value="4">4</option>#}
{#                                </select>#}
{##}
{#                            </div>#}
{#                            <div class="col-6 text-end">#}
{#<button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">Add to basket</button></div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </main>#}
{##}
{#</div>#}
{##}
{#<script>#}
{#    $(document).on('click', '#add-button', function (e) {#}
{#        e.preventDefault();#}
{#        $.ajax({#}
{#            type: 'POST',#}
{#            url: '{% url "basket:basket_add" %}',#}
{#            data: {#}
{#                productid: $('#add-button').val(),#}
{#                productqty: $('#select option:selected').text(),#}
{#                csrfmiddlewaretoken: "{{csrf_token}}",#}
{#                action: 'post'#}
{#            },#}
{#            success: function (json) {#}
{#               document.getElementById("basket-qty").innerHTML = json.qty#}
{#            },#}
{#            error: function (xhr, errmsg, err) {}#}
{#        });#}
{#    })#}
{#</script>#}
{##}
{#{% endblock %}#}

</div>